param(
  [switch]$Enable,
  [switch]$Disable,
  [string]$ProjectRoot = "",
  [string]$ServerUrl = "",
  [string]$HostIp = "",
  [int]$Port = 49321,
  [string]$Token = "",
  [string]$TokenPath = "",
  [string]$ClientName = "tizen-emulator"
)

$ErrorActionPreference = "Stop"

function Test-IsInsidePath {
  param(
    [string]$Path,
    [string]$Root
  )

  $rootWithSeparator = if ($Root.EndsWith([System.IO.Path]::DirectorySeparatorChar)) {
    $Root
  } else {
    $Root + [System.IO.Path]::DirectorySeparatorChar
  }

  return $Path.Equals($Root, [System.StringComparison]::OrdinalIgnoreCase) -or
    $Path.StartsWith($rootWithSeparator, [System.StringComparison]::OrdinalIgnoreCase)
}

function ConvertTo-JsString {
  param([string]$Value)

  return ConvertTo-Json -Compress -InputObject $Value
}

function Set-Utf8NoBomFile {
  param(
    [string]$Path,
    [string]$Value
  )

  $encoding = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($Path, $Value, $encoding)
}

function New-DebugBridgeToken {
  $bytes = New-Object byte[] 24
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $rng.GetBytes($bytes)
  } finally {
    $rng.Dispose()
  }
  return [Convert]::ToBase64String($bytes).TrimEnd("=").Replace("+", "-").Replace("/", "_")
}

function Get-DetectedHostIp {
  $addresses = @(
    [System.Net.Dns]::GetHostAddresses([System.Net.Dns]::GetHostName()) |
      Where-Object {
        $_.AddressFamily -eq [System.Net.Sockets.AddressFamily]::InterNetwork -and
        -not [System.Net.IPAddress]::IsLoopback($_) -and
        -not $_.ToString().StartsWith("169.254.")
      } |
      ForEach-Object {
        $ip = $_.ToString()
        $score = 50
        if ($ip.StartsWith("192.168.")) {
          $score = 0
        } elseif ($ip.StartsWith("10.")) {
          $score = 10
        } elseif ($ip -match "^172\.(1[6-9]|2[0-9]|3[0-1])\.") {
          $score = 20
        }
        [pscustomobject]@{
          Ip = $ip
          Score = $score
        }
      }
  )

  if ($addresses.Count -eq 0) {
    return ""
  }

  return ($addresses | Sort-Object Score, Ip | Select-Object -First 1).Ip
}

function Get-DisabledConfigContent {
  @'
(function() {
  'use strict';

  var config = {
    enabled: false,
    serverUrl: '',
    token: '',
    clientName: 'tizen-emulator'
  };

  try {
    var overrideText = window.localStorage && window.localStorage.getItem('moonlightDebugBridgeConfig');
    if (overrideText) {
      var override = JSON.parse(overrideText);
      if (override && typeof override === 'object') {
        config.enabled = override.enabled === true;
        config.serverUrl = override.serverUrl ? String(override.serverUrl) : '';
        config.token = override.token ? String(override.token) : '';
        config.clientName = override.clientName ? String(override.clientName) : config.clientName;
      }
    }
  } catch (error) {
    config.enabled = false;
    config.serverUrl = '';
    config.token = '';
  }

  window.MOONLIGHT_DEBUG_BRIDGE = window.MOONLIGHT_DEBUG_BRIDGE || config;
})();
'@
}

function Get-EnabledConfigContent {
  param(
    [string]$ResolvedServerUrl,
    [string]$ResolvedToken,
    [string]$ResolvedClientName
  )

  $serverUrlJson = ConvertTo-JsString $ResolvedServerUrl
  $tokenJson = ConvertTo-JsString $ResolvedToken
  $clientNameJson = ConvertTo-JsString $ResolvedClientName

  @"
// Generated by tools/write-debug-bridge-config.ps1 for a local debug build.
// Do not commit enabled debug bridge configs or tokens.
window.MOONLIGHT_DEBUG_BRIDGE = {
  enabled: true,
  serverUrl: $serverUrlJson,
  token: $tokenJson,
  clientName: $clientNameJson
};
"@
}

if ($Enable -and $Disable) {
  throw "Use either -Enable or -Disable, not both."
}

if (-not $Enable -and -not $Disable) {
  $Enable = $true
}

$repoRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")).Path
if ([string]::IsNullOrWhiteSpace($ProjectRoot)) {
  $ProjectRoot = Join-Path $repoRoot "wasm"
}

$projectPath = (Resolve-Path -LiteralPath $ProjectRoot).Path
if (-not (Test-IsInsidePath -Path $projectPath -Root $repoRoot)) {
  throw "ProjectRoot must be inside the repository: $projectPath"
}

$configPath = Join-Path $projectPath "platform\debug_bridge_config.js"
if (-not (Test-Path -LiteralPath (Split-Path -Parent $configPath) -PathType Container)) {
  throw "Missing platform directory: $(Split-Path -Parent $configPath)"
}

if ($Disable) {
  Set-Utf8NoBomFile -Path $configPath -Value (Get-DisabledConfigContent)
  Write-Host "Wrote disabled debug bridge config to $configPath"
  exit 0
}

if ([string]::IsNullOrWhiteSpace($ServerUrl)) {
  $ServerUrl = $env:MOONLIGHT_DEBUG_BRIDGE_URL
}
if ([string]::IsNullOrWhiteSpace($HostIp)) {
  $HostIp = $env:MOONLIGHT_DEBUG_BRIDGE_HOST_IP
}
if ($env:MOONLIGHT_DEBUG_BRIDGE_PORT) {
  $Port = [int]$env:MOONLIGHT_DEBUG_BRIDGE_PORT
}

if ([string]::IsNullOrWhiteSpace($ServerUrl)) {
  if ([string]::IsNullOrWhiteSpace($HostIp)) {
    $HostIp = Get-DetectedHostIp
  }
  if ([string]::IsNullOrWhiteSpace($HostIp)) {
    throw "Unable to detect a host IP address. Re-run with -HostIp or -ServerUrl."
  }
  $ServerUrl = "http://${HostIp}:$Port"
}

if ([string]::IsNullOrWhiteSpace($Token)) {
  $Token = $env:MOONLIGHT_DEBUG_BRIDGE_TOKEN
}
if ([string]::IsNullOrWhiteSpace($TokenPath)) {
  $TokenPath = Join-Path $repoRoot "build\codex-tizen-run\debug_bridge_token.txt"
}

$tokenStoredAtPath = $false
if ([string]::IsNullOrWhiteSpace($Token)) {
  if (Test-Path -LiteralPath $TokenPath -PathType Leaf) {
    $Token = (Get-Content -Raw -LiteralPath $TokenPath).Trim()
    $tokenStoredAtPath = -not [string]::IsNullOrWhiteSpace($Token)
  }
}
if ([string]::IsNullOrWhiteSpace($Token)) {
  $Token = New-DebugBridgeToken
  New-Item -ItemType Directory -Force -Path (Split-Path -Parent $TokenPath) | Out-Null
  Set-Content -LiteralPath $TokenPath -Value $Token -Encoding ASCII
  $tokenStoredAtPath = $true
}

Set-Utf8NoBomFile -Path $configPath -Value (Get-EnabledConfigContent -ResolvedServerUrl $ServerUrl -ResolvedToken $Token -ResolvedClientName $ClientName)

Write-Host "Wrote enabled debug bridge config to $configPath"
Write-Host "Server URL: $ServerUrl"
if ($tokenStoredAtPath) {
  Write-Host "Token: stored in $TokenPath"
} else {
  Write-Host "Token: supplied by parameter or environment"
}
if ($projectPath.Equals((Resolve-Path -LiteralPath (Join-Path $repoRoot "wasm")).Path, [System.StringComparison]::OrdinalIgnoreCase)) {
  Write-Host "Warning: this modifies a tracked source file. Run this script with -Disable before committing."
}
